ProjektKoncowy/urls.py
from django.contrib import admin
from django.urls import path, include
from inwestycje import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('products/', views.ProduktyObecne.as_view(), name='products'),
    path('product/<int:id>/', views.ShowThisProduct.as_view(), name='ten_product'),
    path('accounts/', include('accounts.urls')),  # new
    path('accounts/', include('django.contrib.auth.urls')),
    path('add_product/', views.AddProduct.as_view()),
    path('', views.LoginFormView.as_view()),
    path('logout/', views.logout_view),
    path('product/<int:id>/delete/', views.DeleteObject.as_view()),
    path('product/<int:id>/modify/', views.ModifyThisProduct.as_view()),
    path('category/', views.AddCategory.as_view()),
    path('category/<int:id>/modifycat/', views.ModifyThisCategory.as_view()),
    path('categories/', views.ShowCategories.as_view()),
    path('category/<int:id>/modifycat/delete/', views.DeleteCategory.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

inwestycje/models.py
from django.db import models
from django.contrib.auth.models import User




# nazwa produktu i opis krotki
class Product(models.Model):
    name = models.CharField(max_length=164)
    description = models.TextField()
    profitability = models.FloatField()
    start_date = models.DateField()
    end_date = models.DateField()
    files = models.FileField(upload_to='media/', default='settings.MEDIA_ROOT/media/random_photo.png')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


# Kategoria produktu
class Category(models.Model):
    name = models.CharField(max_length=164)
    product = models.ManyToManyField(Product)

templates/add_category.html
{% extends 'base.html' %}
{% block content %}
<H3>Dodaj kategorie do produktu</H3>
    <form method="post">
        {{ form.as_p }}
       <a href="this_product.html"> <button type="submit">Dodaj</button></a>
{% csrf_token %}
    </form>
{% endblock %}

templates/add_product_form.html
{% extends 'base.html' %}

<div>{% block content %}
    <h3>Dodaj produkt do bazy</h3>
    <form action="" method="post" enctype='multipart/form-data'>
        {{ form.as_p }}
        <a href="">
           <button type="submit">Zapisz</button>
        </a>
        {% csrf_token %}
    </form>

    {% csrf_token %}
{% endblock %}
</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <a href="/categories"><button type="button"> Kategorie</button></a>
    <a href="/products"><button type="button"> Home</button></a>
    <a href="/add_product/"><button type="button"> Dodaj produkt </button></a>
     <a href="/logout"><button type="button"> Wyloguj </button></a>
    <a href="/accounts/signup"><button type="button">Sign up</button></a>
</div>
<div>
    <h1><p>PRODUKTY INWESTYCYJNE</p></h1>
</div>
{% block content %}

{% endblock %}
{% csrf_token %}
</body>
</html>

templates/delete_category.html
{% extends 'base.html' %}
​

​
{% block content %}
​
<form action="" method="post">
{% csrf_token %}

{{ form.as_p }}
<input type="submit" value="Save">
</form>
​
{% endblock %}

templates/delete_product.html
{% extends 'base.html' %}
​

​
{% block content %}
​
<form action="" method="post">
{% csrf_token %}

{{ form.as_p }}
<input type="submit" value="Save">
</form>
​
{% endblock %}

templates/download_doc.html
{% extends 'base.html' %}
{% block content %}
    <h2>Dodaj dokumentacje</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="document">
        <button type="submit">Upload File</button>
    </form>

{% endblock %}

templates/local_page.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        {% for product in products %}
            <a href="{% url 'ten_product' product.id %}">
                <h3>
                    <li>{{ product.name }} {{ product.profitability }} %r.r   </li>
                </h3>
            </a>
        {% endfor %}
    </ul>
    {% if request.user.is_superuser == False %}
        <h4>Łącznie rocznie zarabiam: {{suma}} %</h4>
    {% endif %}
{% endblock %}

templates/log_out.html
{% extends 'base.html' %}
{% block content %}
<h3>Zaloguj się ponownie</h3>
{% endblock %}

templates/login_form.html
{% extends 'base.html' %}
{% block content %}
{{ form.as_p }}
<a href="/{% url 'products' %}"><button type="submit">Zaloguj</button></a>
{% endblock %}

templates/modify.html
{% extends "base.html" %}

{% block content %}
    <h3>Modyfikuj produkt</h3>
    <form method="post">
        {{ form.as_p }}

        <a href="this_product.html">
            <button type="submit">Zapisz</button>
        </a>
        {% csrf_token %}
    </form>
{% endblock %}

templates/modify_category.html
{% extends "base.html" %}

{% block content %}
    <form method="post">
        {{ form.as_p }}

        <a href="this_product.html">
            <button type="submit">Zapisz</button>
        </a>
        {% csrf_token %}
    </form>
    {% if request.user.is_superuser %}
    <a href="delete">
            <button type="submit">Usun Kategorie</button>
        </a><br>
    {% endif %}
{% endblock %}

templates/this_category.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        <h2> Kategorie:</h2>

        {% for cat in categories %}

                <li>{{ cat.name }}</li>

        {% endfor %}


    </ul>


{% endblock %}

templates/this_product.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        <h3>
            <li>Nazwa produktu:</li>
        </h3>
        {{ product.name }}
        <h3>
            <li>Krótki opis:</li>
        </h3>
        {{ product.description }}
        <h3>
            <li>Stopa zwrotu(roczna):</li>
        </h3>
        {{ product.profitability }}%
        <h3>
            <li>Początek inwestycji:</li>
        </h3>
        {{ product.start_date }}
        <h3>
            <li>Koniec inwestycji:</li>
        </h3>
        {{ product.end_date }}
        <h3>
            <li>Dokumenty:</li>
        </h3>
        <a href="{{ product.files.url }}"> {{ product.files.name }}</a>
        <h3>
            Kategoria:</h3>
        {% for category in product.category_set.all %}
            <li><a href="/category/{{ category.id }}/modifycat/"> {{ category.name }}</a></li>
        {% endfor %}
    </ul>

    <a href="delete">
        <button type="submit">usun produkt</button>
    </a><br>
    <p>
        <a href="/category">
            <button type="submit">Dodaj Kategorie</button>
        </a>
    </p>
    {% if request.user.is_superuser %}

        <P>
            <a href="modify">
                <button type="submit">Zmien dane produktu</button>
            </a>
        </P>



    {% endif %}


{% endblock %}